apiVersion: v1
kind: Service
metadata:
  name: aws-iam-authenticator
  namespace: {{ namespace }}
  labels:
    aws-iam: "true"
spec:
  selector:
    k8s-app: "aws-iam-authenticator"
  ports:
  - protocol: TCP
    port: 443
    targetPort: 21362

---